### ISSUE TITLE
persistent banner to alert users that they're morphed, with a link to unmorph

### ISSUE THREAD

**Issue by dpaola2** [Bloc/morphing#3]

**Comment by wordofchristian** [comment]
@dpaola2 I don't think this library should implement UI. UI's tend to be particular and specific to each app. I think the gem user should implement their own UI banner and we simply provide hooks so they can tell if someone is morphed and who they are. Then we could provide a snippet example for implementing that banner.

**Comment by dpaola2** [comment]
I think I agree.
